version: '3.5'

networks:
  nw:
    name: webapp_network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp_volume
    driver_opts:
      type: none
      o: bind
      device: /home/sakkus/data/wordpress
  db:
    driver: local
    name: db_volume
    driver_opts:
      type: none
      o: bind
      device: /home/sakkus/data/mariadb

services:
    mariadb:
      image: mariadb
      container_name: mariadb
      build: ./requirements/mariadb
      env_file:
        - ./requirements/.env
      ports:
        - 3306:3306
      networks:
        - nw
      restart: always
      volumes:
        - db:/var/lib/mysql

    wordpress:
      image: wordpress
      container_name: wordpress
      build: ./requirements/wordpress
      env_file:
        - ./requirements/.env
      ports:
        - "9000:9000"
      depends_on:
        - mariadb
      networks:
        - nw
      volumes:
        - wp:/var/www/html

    nginx:
      image: nginx
      container_name: nginx
      build: ./requirements/nginx
      env_file:
        - ./requirements/.env
      ports:
        - "8080:80"
        - "443:443"
      depends_on:
        - wordpress
      networks:
        - nw
      restart: always
      volumes:
        - wp:/var/www/html